### ISSUE TITLE
Drop flag command spam

### ISSUE THREAD

**Issue by TriForceX** [TriForceX/JediKnightPlus#1]
We need prevent the command spam because if you drop the flag in front of you while running the flag returns to you everytime you use the command. Maybe adding a "drop timer" will fix this problem.

**Comment by LordAttano** [comment]
Either make the flag drop backwards or alternatively just at the location the command was used.

Side note: Has such a feature actually been requested? Sounds like something that could easily be abused in an actual game context?

Perhaps you should also consider adding a _cooldown_ for the usage of the command.

**Comment by TriForceX** [comment]
> Either make the flag drop backwards or alternatively just at the location the command was used.

Yea it can be an option, but he can take it again if it goes back. Anyways i think there should be a "waiting time" before take it again

> Side note: Has such a feature actually been requested? Sounds like something that could easily be abused in an actual game context?

Yea, this feature was requested in the old version of the mod (JKPlus2008). Maybe it can be abused (thats why im trying to prevent the spam or add some penalties to its usage). This was requested mainly because if you have low health and a mate is around you, you can give him the flag without dying with it.

> Perhaps you should also consider adding a cooldown for the usage of the command.

Yea, i was thinking that half of the score won should be subtracted

**Comment by LordAttano** [comment]
> Yea it can be an option, but he can take it again if it goes back. Anyways i think there should be a "waiting time" before take it again

Yes, a cooldown on the same player picking it up would probably be better, as if it dropped backwards as I suggested it could potentially just drop into the lap of whoever is chasing the runner.

> Yea, this feature was requested in the old version of the mod (JKPlus2008). Maybe it can be abused (thats why im trying to prevent the spam or add some penalties to its usage).

Remember to make it possible to disable the feature entirely, if you have not done so already. Haven't checked your code, but I assume you already have a cvar for this purpose.

> Yea, i was thinking that half of the score won should be subtracted

Could be a potential alternative punishment for using the command, however remember that in the grand scheme of things only the _team score_ actually counts for anything in CTF.

**Comment by TriForceX** [comment]
> Yes, a cooldown on the same player picking it up would probably be better, as if it dropped backwards as I suggested it could potentially just drop into the lap of whoever is chasing the runner.

What you mean with "cooldown"? (im not good at English).

> Remember to make it possible to disable the feature entirely, if you have not done so already. Haven't checked your code, but I assume you already have a cvar for this purpose.

Yea it has already a cvar for it, anyways every feature is toggleable in this mod.

> Could be a potential alternative punishment for using the command, however remember that in the grand scheme of things only the team score actually counts for anything in CTF.

You are right, maybe also an instant kill when drop flag could be an option too (haha lol). i will take a look for other options.

**Comment by LordAttano** [comment]
> What you mean with "cooldown"? (im not good at English).

That if someone has _just dropped the flag_ then _that same player_ has to wait for e.g. 5 seconds before they can pick it up again. This would make it a risk to do if no teammates are around, while making it an actual strategy if there _is_ a teammate around, like passing the ball in football and such.

**Comment by TriForceX** [comment]
> That if someone has just dropped the flag then that same player has to wait for e.g. 5 seconds before they can pick it up again. This would make it a risk to do if no teammates are around, while making it an actual strategy if there is a teammate around, like passing the ball in football and such.

Ah yea, thats basically what is expected 👍

**Comment by TriForceX** [comment]
This have been fixed on commit c48adc8
