### ISSUE TITLE
Wrong 2nd click event on Emotes list

### ISSUE THREAD

**Issue by TriForceX** [TriForceX/JediKnightPlus#6]
Theres a bug i recently noticed about clicking an emote on list in-game, the first click play the emote correctly but if i click again the emote is not played, i have to click another emote and back to click the first one if i want play again. This can be solved reseting the "last played emote" or maybe by adding a "play button".

![emote-list](https://user-images.githubusercontent.com/16083854/63444630-fcb2cb80-c404-11e9-95ca-04764ca21e21.png)

**Comment by LordAttano** [comment]
Are the emotes in the menu _hardcoded_ into it or does the server send a list to the client? If they are hardcoded then you should look into how Fau did his menu for custom modes and gametypes. He has it so that the modes which appear to the client are those found in the server mod directory, meaning that he can add new modes and variations for players to vote on without them having to download an entirely new menu.

Not sure about your actual issue though.

**Comment by TriForceX** [comment]
Thats not related with the actual issue but is a good idea, i will consider it.

The issue is you cant play (click) the same emote on list twice or more, it works just the first time the emote is played, you have to play another emote to play the first one again.

**Comment by LordAttano** [comment]
> The issue is you cant play (click) the same emote on list twice or more, it works just the first time the emote is played, you have to play another emote to play the first one again.

In the best of cases it could perhaps be resolved through one of the solutions you laid out yourself. In a worst case it may require some changes to how user interfaces work in general. Not sure if that would require engine changes or if it can be solved through the qvm files.

**Comment by TriForceX** [comment]
Thankfully these solutions doesn't requires engine modifications. I will see if i solve the current one easily, if not i will update it with buttons... something like this:
![image](https://user-images.githubusercontent.com/16083854/63461093-e5d0a100-c425-11e9-9f8a-25fd05a5b443.png)

**Comment by TriForceX** [comment]
This has been fixed in commit 9db1131 using a temporary UI cvar to store the lastest emote index.
